### PR TITLE
Connect round timer to guns and buildings

### PR DESCRIPTION
**Pull request by MagiMaster**
Disable guns while the round isn't running and reset players and buildings at the start of a round. (Buildings just reset to one form for now, but should be randomized.)

### CODE REVIEW

**Review by ChipioIndustries — CHANGES_REQUESTED** [review]
The code looks good, but there is a bug I came across. I was accidentally holding down the mouse button when the round started, which resulted in my gun firing for the entire duration of the round even when I wasn't holding the button down.

**Comment by MagiMaster** [comment]
> The code looks good, but there is a bug I came across. I was accidentally holding down the mouse button when the round started, which resulted in my gun firing for the entire duration of the round even when I wasn't holding the button down.

Ah right. I found that to, but guess I forgot to push the fix. (Err, wait. It looks like my fix is in this. Let me test it a bit more.)

**Comment by MagiMaster** [comment]
I couldn't repro this consistently, but did get it to happen once. I think it's some race condition either clicking or releasing the button right on the timer boundary, and if so, I think the changes I made should make it a lot less likely to fail to clean up. But without being able to reproduce the problem consistently, I can't be sure it's definitely fixed.

**Review by ChipioIndustries — APPROVED** [review]
The issue doesn't seem to be happening anymore for me. 👍

**Pull request merged**
